<?php

namespace Database\Seeders;

use App\Models\MenuModel;
use App\Models\SubMenuModel;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('table_submenu')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        $table_submenu = [
            [
                'menu_id' => '4',
                'submenu' => 'Leader',
                'route_submenu' => 'leader.index',
                'typemenu' => 'view',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Leader',
                // 'route_submenu' => '',
                'typemenu' => 'insert',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Leader',
                // 'route_submenu' => '',
                'typemenu' => 'edit',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Leader',
                // 'route_submenu' => '',
                'typemenu' => 'delete',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Customer',
                'route_submenu' => 'pelanggan.index',
                'typemenu' => 'view',
                'status' => '1',
                'order_submenu' => '2',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Customer',
                // 'route_submenu' => '',
                'typemenu' => 'insert',
                'status' => '1',
                'order_submenu' => '2',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Customer',
                // 'route_submenu' => '',
                'typemenu' => 'edit',
                'status' => '1',
                'order_submenu' => '2',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Customer',
                // 'route_submenu' => '',
                'typemenu' => 'delete',
                'status' => '1',
                'order_submenu' => '2',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Aplikasi',
                'route_submenu' => 'aplikasi.index',
                'typemenu' => 'view',
                'status' => '1',
                'order_submenu' => '3',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Aplikasi',
                // 'route_submenu' => '',
                'typemenu' => 'insert',
                'status' => '1',
                'order_submenu' => '3',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Aplikasi',
                // 'route_submenu' => '',
                'typemenu' => 'edit',
                'status' => '1',
                'order_submenu' => '3',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Aplikasi',
                // 'route_submenu' => '',
                'typemenu' => 'delete',
                'status' => '1',
                'order_submenu' => '3',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Relation',
                'route_submenu' => 'relation.index',
                'typemenu' => 'view',
                'status' => '1',
                'order_submenu' => '4',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Relation',
                // 'route_submenu' => '',
                'typemenu' => 'insert',
                'status' => '1',
                'order_submenu' => '4',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Relation',
                // 'route_submenu' => '',
                'typemenu' => 'edit',
                'status' => '1',
                'order_submenu' => '4',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '4',
                'submenu' => 'Relation',
                // 'route_submenu' => '',
                'typemenu' => 'delete',
                'status' => '1',
                'order_submenu' => '4',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
             [
                'menu_id' => '5',
                'submenu' => 'Pelaporan',
                'route_submenu' => 'pelaporan.index',
                'typemenu' => 'view',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '5',
                'submenu' => 'Pelaporan',
                // 'route_submenu' => '',
                'typemenu' => 'insert',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '5',
                'submenu' => 'Pelaporan',
                // 'route_submenu' => '',
                'typemenu' => 'edit',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '5',
                'submenu' => 'Pelaporan',
                // 'route_submenu' => '',
                'typemenu' => 'delete',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '5',
                'submenu' => 'Penanganan Client',
                'route_submenu' => 'pembelian.index',
                'typemenu' => 'view',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '5',
               'submenu' => 'Penanganan Client',
                // 'route_submenu' => '',
                'typemenu' => 'insert',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '5',
               'submenu' => 'Penanganan Client',
                // 'route_submenu' => '',
                'typemenu' => 'edit',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '5',
               'submenu' => 'Penanganan Client',
                // 'route_submenu' => '',
                'typemenu' => 'delete',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '6',
                'submenu' => 'Laporan',
                'route_submenu' => 'pelanggan.index',
                'typemenu' => 'view',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '6',
                'submenu' => 'Laporan',
                // 'route_submenu' => '',
                'typemenu' => 'insert',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '6',
                'submenu' => 'Laporan',
                // 'route_submenu' => '',
                'typemenu' => 'edit',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
            [
                'menu_id' => '6',
                'submenu' => 'Laporan',
                // 'route_submenu' => '',
                'typemenu' => 'delete',
                'status' => '1',
                'order_submenu' => '1',
                'created_at' => Carbon::now(),
                // 'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($table_submenu as $key => $value) {
            SubMenuModel::create($value);
        }
    }
}
